package com.peaksolution.openatfx.api;

import java.util.Objects;


/**
 * OpenAtfx base attribute.
 * 
 * @author Markus Renner
 */
class AtfxBaseAttribute implements BaseAttribute {

    private final String name;
    private final DataType dataType;
    private final boolean mandatory;
    private final boolean obligatory;
    private final boolean unique;
    private final boolean autogenerated;
    private final BaseElement baseElement;
    private final String enumName;

    /**
     * Constructor.
     * 
     * @param name The name.
     * @param dataType The data type.
     * @param mandatory The mandatory flag.
     * @param obligatory The obligatory flag.
     * @param unique The unique flag.
     * @param autogenerated The autogenerated flag.
     * @param baseElement The base element.
     * @param enumName The enumeration definition.
     */
    public AtfxBaseAttribute(String name, DataType dataType, boolean mandatory, boolean obligatory, boolean unique,
            boolean autogenerated, BaseElement baseElement, String enumName) {
        this.name = name;
        this.dataType = dataType;
        this.mandatory = mandatory;
        this.obligatory = obligatory;
        this.unique = unique;
        this.autogenerated = autogenerated;
        this.baseElement = baseElement;
        this.enumName = enumName;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public DataType getDataType() {
        return this.dataType;
    }

    @Override
    public boolean isMandatory() {
        return this.mandatory;
    }

    @Override
    public boolean isObligatory() {
        return this.obligatory;
    }

    @Override
    public boolean isUnique() {
        return this.unique;
    }

    @Override
    public boolean isAutogenerated() {
        return autogenerated;
    }

    @Override
    public BaseElement getBaseElement() {
        return this.baseElement;
    }

    @Override
    public String getEnumName() {
        return this.enumName;
    }

    @Override
    public String toString() {
        return "AtfxBaseAttribute [name=" + name + ", dataType=" + dataType + ", obligatory=" + obligatory + ", unique="
                + unique + ", autogenerated=" + autogenerated + ", baseElement=" + baseElement
                + ", enumName=" + enumName + "]";
    }

    @Override
    public int hashCode() {
        return Objects.hash(baseElement, name);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AtfxBaseAttribute other = (AtfxBaseAttribute) obj;
        return Objects.equals(baseElement, other.baseElement) && Objects.equals(name, other.name);
    }
}
