package com.peaksolution.openatfx.api;
import com.peaksolution.datamodel.BaseAttribute;
import com.peaksolution.datamodel.DataType;
import com.peaksolution.datamodel.DefaultAttribute;

import java.util.Objects;

import org.asam.ods.ErrorCode;

import com.peaksolution.openatfx.io.AtfxTagConstants;


public class AtfxAttribute extends DefaultAttribute {

    private final AtfxElement parentElement;
    private BaseAttribute baseAttribute;
    private boolean isExtendedCompatibilityMode;

    /**
     * @param element
     * @param attrNo
     * @param name
     * @param baseAttribute
     * @param dt
     * @param unitId
     * @param enumName
     * @param length if set to {@literal <} 1, the default length will be set according to dataType.
     * @param unique
     * @param obligatory
     * @param autogenerated
     * @param isExtendedCompatibilityMode
     */
    public AtfxAttribute(AtfxElement element, int attrNo, String name, BaseAttribute baseAttribute, DataType dt,
            long unitId, String enumName, int length, boolean unique, boolean obligatory, boolean autogenerated,
            boolean isExtendedCompatibilityMode) {
        super(element == null ? 0 : element.getId(), attrNo, name);
        this.parentElement = element;
        setBaseAttribute(baseAttribute);
        if (dt != null) {
            setDataType(dt);
        }
        super.setEnumName(enumName);
        setUnitId(unitId);
        setLength(length);
        setUnique(unique);
        setObligatory(obligatory);
        setAutogenerated(autogenerated);
        this.isExtendedCompatibilityMode = isExtendedCompatibilityMode;
    }

    @Override
    public boolean isBaseAttrDerived() {
        return baseAttribute != null;
    }
    
    @Override
    public boolean isLocalColumnValuesAttr() {
        if (parentElement != null && isBaseAttrDerived()) {
            return AtfxTagConstants.LC.equalsIgnoreCase(parentElement.getType())
                    && AtfxTagConstants.LC_VALUES.equalsIgnoreCase(baseAttribute.getName());
        }
        return false;
    }
    
    @Override
    public boolean isLocalColumnFlagsAttr() {
        if (parentElement != null && isBaseAttrDerived()) {
            return AtfxTagConstants.LC.equalsIgnoreCase(parentElement.getType())
                    && AtfxTagConstants.LC_FLAGS.equalsIgnoreCase(baseAttribute.getName());
        }
        return false;
    }
    
    @Override
    public boolean isLocalColumnGenParamsAttr() {
        if (parentElement != null && isBaseAttrDerived()) {
            return AtfxTagConstants.LC.equalsIgnoreCase(parentElement.getType())
                    && AtfxTagConstants.LC_GEN_PARAMS.equalsIgnoreCase(baseAttribute.getName());
        }
        return false;
    }

    @Override
    public void setName(String newName) {
        // check name length
        if (newName == null || newName.length() < 1) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER, "newName must not be empty");
        }
        if (newName.length() > 30) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER,
                                        "Attribute name must not be greater than 30 characters");
        }
        // check for name equality
        if (getName() != null && getName().equals(newName)) {
            return;
        }
        // check for existing application attribute name
        AtfxAttribute existingAttribute = parentElement.getAttributeByName(newName);
        if (existingAttribute != null) {
            throw new OpenAtfxException(ErrorCode.AO_DUPLICATE_NAME,
                                        "Attribute with name '" + newName + "' already exists for " + parentElement);
        }

        super.setName(newName);
    }

    @Override
    public String getBaseName() {
        if (baseAttribute == null) {
            return null;
        }
        return baseAttribute.getName();
    }

    public BaseAttribute getBaseAttribute() {
        return baseAttribute;
    }

    public void setBaseAttribute(BaseAttribute baseAttribute) {
        if (baseAttribute != null) {
            // check if already an application attribute exists with same base attribute
            Integer existingAttrNo = parentElement.getAttrNoByBaseName(baseAttribute.getName());
            if (existingAttrNo != null && !existingAttrNo.equals(getAttrNo())) {
                throw new OpenAtfxException(ErrorCode.AO_DUPLICATE_BASE_ATTRIBUTE,
                                            "Duplicate base attribute '" + baseAttribute.getName() + "'");
            }

            // set new datatype from base attribute
            if (super.getDataType() == null) {
                super.setDataType(baseAttribute.getDataType());
            }

            // set enumeration definition from base attribute
            DataType currentDt = super.getDataType();
            if (currentDt == DataType.DT_ENUM || currentDt == DataType.DS_ENUM) {
                super.setEnumName(baseAttribute.getEnumName());
            } else {
                super.setEnumName(null);
            }

            super.setUnique(baseAttribute.isUnique());
            super.setObligatory(baseAttribute.isObligatory());
            super.setAutogenerated(baseAttribute.isAutogenerated());
        }

        this.baseAttribute = baseAttribute;
    }

    @Override
    public void setDataType(DataType dataType) {
        if (dataType == null) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER, "Parameter 'dataType' must not be null");
        }

        super.setDataType(dataType);
        setLength(0);
    }

    @Override
    public DataType getDataType() {
        // custom type set
        DataType dataType = super.getDataType();
        if (dataType != null) {
            return dataType;
        }
        // no custom type set use type from base attribute
        else if (this.baseAttribute != null) {
            return this.baseAttribute.getDataType();
        }
        // no datatype, return DT_UNKNOWN
        return DataType.DT_UNKNOWN;
    }

    @Override
    public void setEnumName(String enumName) {
        // incorrect datatype
        DataType dataType = super.getDataType();
        if (DataType.DT_ENUM != dataType && DataType.DS_ENUM != dataType) {
            throw new OpenAtfxException(ErrorCode.AO_INVALID_DATATYPE,
                                        "Invalid datatype " + dataType
                                                + " to get enumeration from attribute '" + getName() + "' at element '"
                                                + parentElement.getName() + "'.");
        }
        // check for equality
        if (enumName != null && enumName.equals(getEnumName())) {
            return;
        }

        if (!isExtendedCompatibilityMode && this.baseAttribute != null) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER,
                                        "changing the enumeration definition not allowed for application attribute derived from base attribute");
        }
        super.setEnumName(enumName);
    }

    @Override
    public void setLength(Integer length) {
        if (length != null && length > 0) {
            super.setLength(length);
        } else {
            // set default length
            DataType dt = getDataType();
            if (dt == DataType.DT_STRING || dt == DataType.DS_STRING || dt == DataType.DT_EXTERNALREFERENCE
                    || dt == DataType.DS_EXTERNALREFERENCE) {
                super.setLength(254);
            } else if (dt == DataType.DT_DATE || dt == DataType.DS_DATE) {
                super.setLength(30);
            } else {
                super.setLength(1);
            }
        }
    }

    @Override
    public void setUnique(boolean unique) {
        // it is not allowed to reduce the unique flag from base attribute
        if (this.baseAttribute != null && !unique && this.baseAttribute.isUnique()) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER,
                                        "Reducing the uniqueness of attributes derived from unique base attributes is not allowed [element="
                                                + parentElement.getName() + ", aaName=" + getName() + ",baName="
                                                + baseAttribute.getName() + "]");
        }
        super.setUnique(unique);
    }

    @Override
    public void setObligatory(boolean obligatory) {
        // obligatory flag of obligatory base attribute is not reducible
        boolean mustBeObligatory = false;
        String baseAttributeName = null;
        String baseElementName = null;
        if (this.baseAttribute != null && baseAttribute.isObligatory()) {
            mustBeObligatory = true;
        }
        if (mustBeObligatory && !obligatory) {
            if (isExtendedCompatibilityMode) {
                super.setObligatory(true);
            } else {
                throw new OpenAtfxException(ErrorCode.AO_IS_BASE_ATTRIBUTE,
                                            "Unable to set obligatory flag to 'false' for application attribute derived"
                                                    + " from the obligatory base attribute '" + baseAttributeName
                                                    + "' of base element" + " '" + baseElementName + "'.");
            }
        }

        super.setObligatory(obligatory);
    }

    @Override
    public boolean isObligatory() {
        // if the base attribute is obligatory, always return true
        if (this.baseAttribute != null && baseAttribute.isObligatory()) {
            return true;
        }
        return super.isObligatory();
    }

    @Override
    public void setAutogenerated(boolean autogenerated) {
        // it is not allowed to reduce the autogenerated flag from base attribute
        if (this.baseAttribute != null && !autogenerated && this.baseAttribute.isAutogenerated()) {
            throw new OpenAtfxException(ErrorCode.AO_BAD_PARAMETER,
                                        "Autogeneration of attribute derived from autogenerated base attribute cannot be removed [element="
                                                + parentElement.getName() + ", aaName=" + getName() + ",baName="
                                                + baseAttribute.getName() + "]");
        }
        super.setAutogenerated(autogenerated);
    }

    @Override
    public String toString() {
        return "Attribute [aid=" + getAid() + ", name=" + getName() + (baseAttribute == null ? "" : ", baseName=" + baseAttribute.getName()) + ", dt="
                + getDataType() + ", unitId=" + getUnitId() + "]";
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAid(), getName());
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        AtfxAttribute other = (AtfxAttribute) obj;
        return getAid() == other.getAid() && Objects.equals(getName(), other.getName());
    }
}
