package com.peaksolution.openatfx.api;

public interface Attribute {
    long getAid();
    
    int getAttrNo();
    
    String getName();
    
    String getBaseName();
    
    DataType getDataType();
    
    long getUnitId();
    
    String getEnumName();

    int getLength();

    boolean isUnique();

    boolean isObligatory();

    boolean isAutogenerated();

    void setName(String name);
    
    void setDataType(DataType newDataType);

    void setObligatory(boolean obligatory);

    void setUnique(boolean unique);

    void setLength(Integer length);

    void setEnumName(String enumName);

    void setUnitId(long unitId);

    boolean isBaseAttrDerived();
    
    boolean isLocalColumnValuesAttr();

    boolean isLocalColumnFlagsAttr();

    boolean isLocalColumnGenParamsAttr();
}
