package com.peaksolution.openatfx.api;

public interface BaseAttribute {

    public String getName();

    public DataType getDataType();

    boolean isMandatory();

    public boolean isObligatory();

    public boolean isUnique();

    boolean isAutogenerated();

    public BaseElement getBaseElement();

    public String getEnumName();
}
