package com.peaksolution.openatfx.api;

import java.util.Objects;


class TempAttribute {

    public long aid = 0;
    public String name = null;
    public String baseName = null;
    public DataType dataType = DataType.DT_UNKNOWN;
    public long unitId = 0;
    public String enumName = null;
    public int length = 0;
    public Boolean unique = null;
    public Boolean obligatory = null;
    public Boolean autogenerated = null;

    @Override
    public String toString() {
        return "TempAttribute [aid=" + aid + ", name=" + name + ", baseName=" + baseName + ", dt=" + dataType
                + ", unitName=" + unitId + "]";
    }

    @Override
    public int hashCode() {
        return Objects.hash(aid, name);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        TempAttribute other = (TempAttribute) obj;
        return aid == other.aid && Objects.equals(name, other.name);
    }
}
