name: Upload ZIP Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ZIP
        run: mvn clean install -DskipTests assembly:single

      - name: Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.zip
