name: Upload ZIP Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ZIP
        run: mvn clean install -DskipTests assembly:single

      - name: Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.zip
          tag_name: v${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Release tag for openATFX ${{ github.ref_name }} created by GitHub Action"
