name: Build and Publish Maven Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Install Maven
        run: |
          sudo apt-get install maven

      - name: Build and License check
        run: mvn clean package dependency-check:aggregate assembly:single -Plicense,owasp

      - name: Deploy to Maven Central
        if: github.ref == 'refs/heads/main'
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          sudo apt-get install gnupg
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          mvn clean deploy -P release -DskipTests -Dgpg.passphrase=$GPG_PASSPHRASE
